### ISSUE TITLE
Resource can't start

### ISSUE THREAD

**Issue by TruongVoKyDeep** [jet2tlf/mongodb#1]
![image](https://github.com/jet2tlf/mongodb/assets/91012643/36386eb2-8087-4b61-94d6-383f3973946b)

**Comment by jet2tlf** [comment]
Download the release v1.0.0, you downloaded it directly from the main branch, this version was made to be compiled with esbuild, it cannot be compiled directly within FiveM. I forgot to specify this in the readme, I apologize

**Comment by jet2tlf** [comment]
Download the release v1.0.0, you downloaded it directly from the main branch, this version was made to be compiled with esbuild, it cannot be compiled directly within FiveM
